# Generated by Django 2.0 on 2022-02-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Num', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Another_name', models.CharField(max_length=30)),
                ('calling_status', models.CharField(choices=[('Follow Up', 'Follow-Up'), ('Booked SomeWhere', 'Booked Somewhere'), ('Not Interested', 'Not Interested'), ('Need Something', 'Need Something'), ('GH Booking', 'GH Booking')], default='Follow-Up', max_length=20)),
                ('Date', models.DateField()),
                ('type_function', models.CharField(choices=[('Wedding', 'Wedding'), ('Prewedding', 'Prewedding'), ('Retairement', 'Retairement'), ('Shooting', 'Shooting'), ('Mics', 'Mics')], default='Wedding', max_length=20)),
                ('Guests', models.IntegerField()),
                ('Decoration', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('Food', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Customer_Budget', models.IntegerField()),
                ('Price_Quoted', models.TextField(max_length=30)),
                ('Prince_Finalized', models.TextField(max_length=30)),
                ('Discount_given', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Comments', models.TextField(max_length=500)),
                ('system', models.DateField()),
                ('Lead_number_generated', models.IntegerField()),
            ],
        ),
    ]
