# Generated by Django 2.0 on 2022-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_model',
            name='Comments',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Price_Quoted',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Prince_Finalized',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='system',
            field=models.DateField(auto_now_add=True),
        ),
    ]
