# Generated by Django 2.0 on 2022-02-08 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20220208_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_model',
            name='system',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
