# Generated by Django 2.0 on 2022-02-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20220208_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_model',
            old_name='Phone_Num',
            new_name='Phone_Number',
        ),
    ]
