# Generated by Django 2.0 on 2022-02-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20220208_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_model',
            old_name='calling_status',
            new_name='Current_status',
        ),
        migrations.AddField(
            model_name='web_model',
            name='Calling_status',
            field=models.CharField(choices=[('Follow-Up', 'Follow-Up'), ('New', 'New')], default='New', max_length=20),
        ),
    ]
