# Generated by Django 2.0 on 2022-02-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20220208_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lead_Number', models.CharField(max_length=30)),
                ('Customer_Number', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=30)),
                ('Date_Of_Function', models.DateField()),
                ('Price_Agreed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
                ('Total_amount_Received_So_Far', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30)),
                ('Add_Money', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=30)),
                ('Email_Receipt', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30)),
                ('Print_Receipt', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20)),
            ],
        ),
    ]
