# Generated by Django 2.0 on 2022-02-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_finance_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance_model',
            old_name='Customer_Number',
            new_name='Customer_Phone_Number',
        ),
    ]
