# Generated by Django 4.0.2 on 2022-02-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20220209_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_model',
            old_name='Date',
            new_name='Date_Of_Function',
        ),
    ]
