# Generated by Django 4.0.2 on 2022-02-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_rename_date_web_model_date_of_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
