# Generated by Django 4.0.2 on 2022-02-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_alter_web_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
