# Generated by Django 4.0.2 on 2022-02-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_alter_finance_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_model',
            name='Comments',
            field=models.TextField(max_length=10),
        ),
    ]
