# Generated by Django 4.0.2 on 2022-02-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_alter_web_model_another_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_model',
            name='Lead_number_generated',
        ),
        migrations.RemoveField(
            model_name='web_model',
            name='system',
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Calling_status',
            field=models.CharField(blank=True, choices=[('Follow-Up', 'Follow-Up'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Comments',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Current_status',
            field=models.CharField(blank=True, choices=[('Follow Up', 'Follow-Up'), ('Booked SomeWhere', 'Booked Somewhere'), ('Not Interested', 'Not Interested'), ('Need Something', 'Need Something'), ('GH Booking', 'GH Booking')], default='Follow-Up', max_length=20),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Customer_Budget',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Decoration',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Discount_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Food',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Guests',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Price_Quoted',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Prince_Finalized',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='type_function',
            field=models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Prewedding', 'Prewedding'), ('Retairement', 'Retairement'), ('Shooting', 'Shooting'), ('Mics', 'Mics')], default='Wedding', max_length=20),
        ),
    ]
