# Generated by Django 4.0.2 on 2022-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_remove_web_model_lead_number_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_model',
            name='Customer_Budget',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Date_Of_Function',
            field=models.DateField(blank=True),
        ),
    ]
