# Generated by Django 4.0.2 on 2022-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_alter_web_model_customer_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_model',
            name='Comments',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Date_Of_Function',
            field=models.DateField(blank=True, null=True),
        ),
    ]
