# Generated by Django 4.0.2 on 2022-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_alter_web_model_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_model',
            name='Add_Money',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Email_Receipt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Price_Agreed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Print_Receipt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Total_amount_Received_So_Far',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Calling_status',
            field=models.CharField(blank=True, choices=[('Follow-Up', 'Follow-Up'), ('New', 'New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Current_status',
            field=models.CharField(blank=True, choices=[('Follow Up', 'Follow-Up'), ('Booked SomeWhere', 'Booked Somewhere'), ('Not Interested', 'Not Interested'), ('Need Something', 'Need Something'), ('GH Booking', 'GH Booking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Decoration',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='type_function',
            field=models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Prewedding', 'Prewedding'), ('Retairement', 'Retairement'), ('Shooting', 'Shooting'), ('Mics', 'Mics')], max_length=20),
        ),
    ]
