# Generated by Django 4.0.2 on 2022-02-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_alter_finance_model_add_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_model',
            name='Date_Of_Function',
        ),
    ]
