# Generated by Django 4.0.2 on 2022-02-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_alter_web_model_date_of_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_model',
            name='Date_Of_Function',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Phone_Number',
            field=models.IntegerField(unique=True),
        ),
    ]
