# Generated by Django 4.0.2 on 2022-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_web_model_added_into_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_model',
            name='Add_Money',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Customer_Phone_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Date_Of_Function',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Email_Receipt',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Lead_Number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Price_Agreed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Print_Receipt',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Total_amount_Received_So_Far',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
    ]
