# Generated by Django 4.0.2 on 2022-02-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0025_alter_finance_model_add_money_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_model',
            old_name='id',
            new_name='Lead_Number',
        ),
    ]
