# Generated by Django 4.0.2 on 2022-02-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0026_rename_id_web_model_lead_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_model',
            old_name='Lead_Number',
            new_name='id',
        ),
    ]
