# Generated by Django 4.0.2 on 2022-02-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_rename_lead_number_web_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_model',
            name='Lead_Number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
