# Generated by Django 4.0.2 on 2022-02-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0028_web_model_lead_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_model',
            name='Lead_Number',
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Phone_Number',
            field=models.PositiveIntegerField(max_length=10, unique=True),
        ),
    ]
