# Generated by Django 4.0.2 on 2022-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0029_remove_web_model_lead_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Phone_Number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
