# Generated by Django 4.0.2 on 2022-02-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0030_remainder_alter_web_model_guests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remainder_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Phone_Number', models.PositiveIntegerField(unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Remainder',
        ),
    ]
