# Generated by Django 4.0.2 on 2022-02-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0032_remove_remainder_model_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder_model',
            name='Date_And_Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Added_Into_System',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
