# Generated by Django 4.0.2 on 2022-02-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0033_alter_remainder_model_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder_model',
            name='remainder_Date',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
        migrations.AddField(
            model_name='remainder_model',
            name='remainder_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
