# Generated by Django 4.0.2 on 2022-02-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0035_rename_remainder_date_remainder_model_remainder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder_model',
            name='Comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='remainder_model',
            name='Remainder_Time',
            field=models.TimeField(blank=True, help_text='Please use the following format< <em>H:M:S</em>>.', null=True),
        ),
    ]
