# Generated by Django 4.0.2 on 2022-02-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0036_remainder_model_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_model',
            old_name='Prince_Finalized',
            new_name='Price_Finalized',
        ),
        migrations.AlterField(
            model_name='remainder_model',
            name='Remainder_Time',
            field=models.TimeField(blank=True, help_text='Please use the following format< <em>H:M</em>>.', null=True),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Name',
            field=models.CharField(help_text=' This Field is Required', max_length=30),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Phone_Number',
            field=models.PositiveIntegerField(help_text=' This Field is Required', unique=True),
        ),
    ]
