# Generated by Django 4.0.2 on 2022-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0037_rename_prince_finalized_web_model_price_finalized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Date_Of_Function',
            field=models.DateField(blank=True, help_text='use this format:<em>YYYY-MM-DD</em>', null=True),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Name',
            field=models.CharField(help_text=' This Field is Required(*)', max_length=30),
        ),
        migrations.AlterField(
            model_name='web_model',
            name='Phone_Number',
            field=models.PositiveIntegerField(help_text=' This Field is Required(*)', unique=True),
        ),
    ]
