# Generated by Django 4.0.2 on 2022-02-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0038_sign_up_model_alter_web_model_date_of_function_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up_model',
            old_name='user_name',
            new_name='username',
        ),
    ]
