# Generated by Django 4.0 on 2022-03-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0039_rename_user_name_sign_up_model_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_Up_Model',
        ),
        migrations.RemoveField(
            model_name='finance_model',
            name='Email_Receipt',
        ),
        migrations.RemoveField(
            model_name='finance_model',
            name='Print_Receipt',
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Add_Money',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Price_Agreed',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Total_amount_Received_So_Far',
            field=models.CharField(max_length=30),
        ),
    ]
