# Generated by Django 4.0 on 2022-03-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0040_delete_sign_up_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance_model',
            old_name='Customer_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='finance_model',
            old_name='Customer_Phone_Number',
            new_name='Phone_Number',
        ),
    ]
