# Generated by Django 4.0 on 2022-03-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0041_rename_customer_name_finance_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance_model',
            old_name='Lead_Number',
            new_name='Customer_Name',
        ),
        migrations.RenameField(
            model_name='finance_model',
            old_name='Phone_Number',
            new_name='Customer_Phone_Number',
        ),
        migrations.RemoveField(
            model_name='finance_model',
            name='Date_Of_Function',
        ),
        migrations.RemoveField(
            model_name='finance_model',
            name='Name',
        ),
    ]
