# Generated by Django 4.0 on 2022-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0042_rename_lead_number_finance_model_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance_model',
            old_name='Customer_Name',
            new_name='Lead_Number',
        ),
        migrations.RenameField(
            model_name='finance_model',
            old_name='Customer_Phone_Number',
            new_name='Phone_Number',
        ),
        migrations.AddField(
            model_name='finance_model',
            name='Function_Date',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
        migrations.AddField(
            model_name='finance_model',
            name='Name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
