# Generated by Django 4.0 on 2022-03-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0043_rename_customer_name_finance_model_lead_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainder_model',
            old_name='Comments',
            new_name='Comment',
        ),
    ]
