# Generated by Django 4.0 on 2022-03-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0044_rename_comments_remainder_model_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance_model',
            old_name='Function_Date',
            new_name='Date_Of_Function',
        ),
    ]
