# Generated by Django 4.0 on 2022-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0045_rename_function_date_finance_model_date_of_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_model',
            name='Email_Receipt',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AddField(
            model_name='finance_model',
            name='Print_Receipt',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finance_model',
            name='Date_Of_Function',
            field=models.DateField(blank=True, null=True),
        ),
    ]
