# Generated by Django 4.0 on 2022-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0046_finance_model_email_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder_model',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
