# Generated by Django 4.0 on 2022-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0047_alter_remainder_model_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_model',
            name='Phone_Number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
