# Generated by Django 4.0 on 2022-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0048_alter_finance_model_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_model',
            name='Phone_Number',
            field=models.IntegerField(unique=True),
        ),
    ]
