# Generated by Django 4.0 on 2022-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0049_alter_finance_model_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_model',
            name='Total_Amount_Status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Incompleted', 'Incompleted')], max_length=20),
        ),
    ]
