# Generated by Django 4.0 on 2022-03-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0050_finance_model_total_amount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder_model',
            name='Calling_status',
            field=models.CharField(blank=True, choices=[('call-back', 'call-back'), ('declined', 'declined'), ('answered', 'answered')], max_length=20),
        ),
    ]
