# Generated by Django 4.0 on 2022-03-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0051_alter_remainder_model_calling_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_model',
            name='Lead_Number',
        ),
    ]
