# Generated by Django 4.0 on 2022-03-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0052_remove_finance_model_lead_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder_model',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.web_model'),
        ),
    ]
