# Generated by Django 4.0 on 2022-03-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0053_remainder_model_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainder_model',
            name='person',
        ),
    ]
