# Generated by Django 4.0 on 2022-03-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0054_remove_remainder_model_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_model',
            name='fin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.finance_model'),
        ),
    ]
