# Generated by Django 4.0 on 2022-03-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0055_web_model_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_model',
            name='fin',
        ),
        migrations.AddField(
            model_name='web_model',
            name='Fin',
            field=models.ManyToManyField(blank=True, to='WebApp.Finance_Model'),
        ),
    ]
